/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * attendance.java
 *
 * Created on May 19, 2010, 11:17:52 PM
 */

package chessimal12;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;

import java.util.Date;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;



/**
 *
 * @author PC
 */
public class attendance extends javax.swing.JFrame {
    String id = "12q";
    DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd");
    int incre = 0;
    /** Creates new form attendance */
    public attendance() {
        initComponents();
        
        jdate1.setDate(new Date());
        b11.setEnabled(false);
        jcom12.setEnabled(false);
 




        try {
            Connection con = DB.getMyConnection();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("select distinct date from atten where id in (select stuid from students where groupstu='"+Home1.selectedGroup+"')");
            Vector v2 = new Vector();
            v2.add("select Date");
            while(rs.next()){


            v2.add(rs.getString("date"));
            jcom12.setModel(new DefaultComboBoxModel(v2));

            }


        } catch (Exception e) {
            System.out.println(e);
        }


            DefaultTableModel df = (DefaultTableModel) jtb1.getModel();
            df.setRowCount(0);
        try {
            Connection con = DB.getMyConnection();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("select a.stuid, a.Nameinit, sum(b.val) as c from students a,atten b where a.stuid=b.id && a.groupstu='"+Home1.selectedGroup+"' group by a.stuid,a.Nameinit");
            while(rs.next()){
            Vector v2 = new Vector();
            id = rs.getString("a.stuid");
            v2.add(rs.getString("a.Stuid"));
            v2.add(rs.getString("a.Nameinit"));
            v2.add(rs.getString("c"));
            df.addRow(v2);
            }


        } catch (Exception e) {
            System.out.println(e);
        }


        
      DefaultTableModel df1 = (DefaultTableModel) jtb1.getModel();
       String date12 = dateFormat.format(jdate1.getDate());

        int rows = df1.getRowCount();

        try {
            Statement st = DB.getMyConnection().createStatement();

       for(int i=0;i<rows;i++){
         ResultSet rs1 = st.executeQuery("select val from atten where id='"+String.valueOf(df1.getValueAt(i, 0))+"' && date ='"+date12+"'");
         if(rs1.next()){
         jtb1.setValueAt(rs1.getString("val").equals("1") ? true : false,i,3);
        }

      }
            } catch (Exception e) {
                System.out.println(e);
        }


       

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtb1 = new javax.swing.JTable();
        jdate1 = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        b11 = new javax.swing.JButton();
        jcom12 = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();

        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Attendance");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtb1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Name", "count", "check"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtb1.getTableHeader().setReorderingAllowed(false);
        jtb1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtb1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtb1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 75, 482, 223));

        jdate1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jdate1.setDateFormatString("yyyy,MM,dd");
        jdate1.setFocusCycleRoot(true);
        getContentPane().add(jdate1, new org.netbeans.lib.awtextra.AbsoluteConstraints(398, 35, 116, -1));

        jButton1.setText("Mark");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(438, 379, 76, -1));

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 379, 71, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel1.setText("Note*  Chnage button is to mark attendance one by one");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 347, -1, -1));

        jButton3.setText("change");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(352, 379, 76, -1));

        jLabel2.setText("Search Attendance of another Day");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 316, -1, 21));

        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 316, -1, -1));

        b11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/search_16.png"))); // NOI18N
        b11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b11ActionPerformed(evt);
            }
        });
        getContentPane().add(b11, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 320, 40, 21));

        getContentPane().add(jcom12, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 320, 133, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/pencil_48.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 15, 270, 50));

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-547)/2, (screenSize.height-480)/2, 547, 480);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jtb1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtb1MouseClicked
        Object i= jtb1.getValueAt(jtb1.getSelectedRow(),3);
        String date = dateFormat.format(jdate1.getDate());

        try {
            Statement st =DB.getMyConnection().createStatement();

        if(String.valueOf(i).equals("true")){
            String incri =String.valueOf(Integer.parseInt((String) jtb1.getValueAt(jtb1.getSelectedRow(),2))+1);
             jtb1.setValueAt(incri, jtb1.getSelectedRow(), 2);
           
        }else if(String.valueOf(i).equals("false")){
            String decri=String.valueOf(Integer.parseInt((String) jtb1.getValueAt(jtb1.getSelectedRow(),2))-1);
            jtb1.setValueAt(decri, jtb1.getSelectedRow(), 2);
        }
        
        } catch (Exception e) {
           Object[] options = {"Ok"};

    int respon = JOptionPane.showOptionDialog(null, "The attendance for "+date+" has been marked", "Warning",JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE,null, options, options[0]);
        if(respon==0){
        this.dispose();
        }
        }
       
    }//GEN-LAST:event_jtb1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String date = dateFormat.format(jdate1.getDate());
        DefaultTableModel df = (DefaultTableModel) jtb1.getModel();
        int rows = df.getRowCount();
        
        try {
            Statement st = DB.getMyConnection().createStatement();
        for(int i=0;i<rows;i++)
        {
        String val1 = String.valueOf(df.getValueAt(i, 3)).equals("true") ? "1" : "0";
        String id1 = (String)df.getValueAt(i, 0);
        st.executeUpdate("insert into atten(val,id,date) values('"+val1+"','"+id1+"','"+date+"')");   
}
            } catch (Exception e) {
             JOptionPane.showMessageDialog(null, "Attendance for this day has been marked");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
String date112 = dateFormat.format(jdate1.getDate());
        String tablevalu;
        try {
            tablevalu = (String)jtb1.getValueAt(jtb1.getSelectedRow(), 0);
            Statement st = DB.getMyConnection().createStatement();
                           
            String val2 = String.valueOf(jtb1.getValueAt(jtb1.getSelectedRow(), 3)).equals("true") ? "1" : "0";
            st.executeUpdate("update atten set val='"+val2+"',date='"+date112+"' where id = '"+tablevalu+"' && date='"+date112+"' ");

  } catch (Exception e) {
            System.out.println(e);
             JOptionPane.showMessageDialog(null,"Please select student before useing this");
        }
       
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        
}//GEN-LAST:event_jButton4ActionPerformed

    private void b11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b11ActionPerformed
      DefaultTableModel df1 = (DefaultTableModel) jtb1.getModel();
      String date12 = (String) jcom12.getSelectedItem();
        int rows = df1.getRowCount();
        try {
            Statement st = DB.getMyConnection().createStatement();
       for(int i=0;i<rows;i++){
         ResultSet rs1 = st.executeQuery("select val from atten where id='"+String.valueOf(df1.getValueAt(i, 0))+"' && date ='"+date12+"'");
         if(rs1.next()){
             System.out.println(rs1.getString("val"));
         jtb1.setValueAt(rs1.getString("val").equals("1") ? true : false,i,3);
        }

      }
            } catch (Exception e) {
                System.out.println(e);
        }
    }//GEN-LAST:event_b11ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
      b11.setEnabled(jRadioButton1.isSelected());
        jcom12.setEnabled(jRadioButton1.isSelected());
        jdate1.setEnabled(!jRadioButton1.isSelected());
        jButton3.setEnabled(!jRadioButton1.isSelected());
        jButton1.setEnabled(!jRadioButton1.isSelected());
        
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new attendance().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b11;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox jcom12;
    private com.toedter.calendar.JDateChooser jdate1;
    private javax.swing.JTable jtb1;
    // End of variables declaration//GEN-END:variables

}
