/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Home1.java
 *
 * Created on May 19, 2010, 7:17:08 PM
 */
package chessimal12;

import de.javasoft.plaf.synthetica.SyntheticaBlackStarLookAndFeel;
import java.awt.Color;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.UIManager;

/**
 *
 * @author PC
 */
public class Home1 extends javax.swing.JFrame {

    public static String selectedGroup = "select group";

    /** Creates new form Home1 */
    public Home1() {
        initComponents();
        DB.ChangeJframeImage(this);
        b6.setEnabled(false);
        t11.setEnabled(false);
        t12.setEnabled(false);

        b2.setEnabled(false);
        b3.setEnabled(false);
        b4.setEnabled(false);
        b5.setEnabled(false);


        selectedGroup = group.getSelectedItem().toString();
        System.out.println(selectedGroup);
        try {
            Connection con = DB.getMyConnection();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("select* from groupstr");


            Vector v1 = new Vector();
            v1.add("select group");


            while ((rs.next())) {

                v1.add(rs.getString("grName"));
                group.setModel(new DefaultComboBoxModel(v1));

            }

        } catch (Exception e) {
            System.out.println(e);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jComboBox1 = new javax.swing.JComboBox();
        group = new javax.swing.JComboBox();
        b1 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        b3 = new javax.swing.JButton();
        b4 = new javax.swing.JButton();
        b5 = new javax.swing.JButton();
        b6 = new javax.swing.JButton();
        t11 = new javax.swing.JButton();
        t12 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        t14 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ChessManager 1.2 makes work easy");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        group.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "group1" }));
        group.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                groupActionPerformed(evt);
            }
        });
        getContentPane().add(group, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 20, 138, -1));

        b1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/user_16.png"))); // NOI18N
        b1.setText("Students");
        b1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });
        getContentPane().add(b1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 170, -1));

        b2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/address_16.png"))); // NOI18N
        b2.setText("Game details");
        b2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });
        getContentPane().add(b2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 170, -1));

        b3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/diagram_16.png"))); // NOI18N
        b3.setText("Progress");
        b3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });
        getContentPane().add(b3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 170, -1));

        b4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bookmark_16.png"))); // NOI18N
        b4.setText("Create Team");
        b4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ActionPerformed(evt);
            }
        });
        getContentPane().add(b4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 170, -1));

        b5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/delete_16.png"))); // NOI18N
        b5.setText("Attendance  ");
        b5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        b5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5ActionPerformed(evt);
            }
        });
        getContentPane().add(b5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 170, -1));

        b6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Boss.png"))); // NOI18N
        b6.setText("Top Players");
        b6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        b6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b6ActionPerformed(evt);
            }
        });
        getContentPane().add(b6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 170, -1));

        t11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/diagram_16.png"))); // NOI18N
        t11.setText("Tournament Details  ");
        t11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        t11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t11ActionPerformed(evt);
            }
        });
        getContentPane().add(t11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 170, -1));

        t12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/clipboard_16.png"))); // NOI18N
        t12.setText("PDF Lessons");
        t12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        t12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t12ActionPerformed(evt);
            }
        });
        getContentPane().add(t12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 170, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Copyrighted © Isite96 2010. All Rights Reserved");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel2MouseExited(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 440, 240, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/briefcase_16.png"))); // NOI18N
        jLabel4.setText("Account Settings");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel4MouseExited(evt);
            }
        });
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, 150, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/task.JPG"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 434, 600, 30));

        t14.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        t14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/info_16.png"))); // NOI18N
        t14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t14ActionPerformed(evt);
            }
        });
        getContentPane().add(t14, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 20, 30, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/chess.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 430));

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-609)/2, (screenSize.height-494)/2, 609, 494);
    }// </editor-fold>//GEN-END:initComponents

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        students1 s1 = new students1();
        s1.setVisible(true);

    }//GEN-LAST:event_b1ActionPerformed

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed

        new progress().setVisible(true);
    }//GEN-LAST:event_b3ActionPerformed

    private void b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ActionPerformed

        new creatTeam1().setVisible(true);
    }//GEN-LAST:event_b4ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed

        new gameDetails().setVisible(true);
    }//GEN-LAST:event_b2ActionPerformed

    private void b5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5ActionPerformed

        new attendance().setVisible(true);
    }//GEN-LAST:event_b5ActionPerformed

    private void b6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b6ActionPerformed

        new topplayers().setVisible(true);
    }//GEN-LAST:event_b6ActionPerformed

    private void t11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t11ActionPerformed

        new tounament().setVisible(true);
    }//GEN-LAST:event_t11ActionPerformed

    private void t12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t12ActionPerformed
        new pdfalternate().setVisible(true);
        //new PdfLessons().setVisible(true);
    }//GEN-LAST:event_t12ActionPerformed

    private void jLabel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseEntered
        jLabel4.setForeground(Color.red);
    }//GEN-LAST:event_jLabel4MouseEntered

    private void jLabel4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseExited
        jLabel4.setForeground(Color.white);
    }//GEN-LAST:event_jLabel4MouseExited

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        new UserChange1().setVisible(true);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void t14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t14ActionPerformed
        this.dispose();
        new new_group().setVisible(true);
    }//GEN-LAST:event_t14ActionPerformed

    private void groupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_groupActionPerformed
        selectedGroup = group.getSelectedItem().toString();
        if (group.getSelectedIndex() == 0) {

            b2.setEnabled(false);
            b3.setEnabled(false);
            b4.setEnabled(false);
            b5.setEnabled(false);
            b6.setEnabled(false);

        } else {
            b2.setEnabled(true);
            b3.setEnabled(true);
            b4.setEnabled(true);
            b5.setEnabled(true);
            b6.setEnabled(true);
            t11.setEnabled(true);
            t12.setEnabled(true);
        }
    }//GEN-LAST:event_groupActionPerformed

    private void jLabel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseEntered
        jLabel2.setForeground(Color.red);
    }//GEN-LAST:event_jLabel2MouseEntered

    private void jLabel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseExited
        jLabel2.setForeground(Color.white);
    }//GEN-LAST:event_jLabel2MouseExited

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        new contact().setVisible(true);
    }//GEN-LAST:event_jLabel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                try {
                    UIManager.setLookAndFeel(new SyntheticaBlackStarLookAndFeel());
                } catch (Exception e) {
                }
                new Home1().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JButton b3;
    private javax.swing.JButton b4;
    private javax.swing.JButton b5;
    private javax.swing.JButton b6;
    private javax.swing.JComboBox group;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton t11;
    private javax.swing.JButton t12;
    private javax.swing.JButton t14;
    // End of variables declaration//GEN-END:variables
}
