/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * jfilechose.java
 *
 * Created on May 29, 2010, 7:25:10 PM
 */

package chessimal12;

import de.javasoft.plaf.synthetica.SyntheticaBlackStarLookAndFeel;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
/**
 *
 * @author PC
 */
public class jfilechose extends javax.swing.JFrame {
addStu addstud;
    void myfile1(addStu s1){

        addstud = s1;
   
    }


    public static File file1;

    /** Creates new form jfilechose */
    public jfilechose() {
        initComponents();
        DB.ChangeJframeImage(this);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);

        jFileChooser1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFileChooser1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jFileChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jFileChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-518)/2, (screenSize.height-319)/2, 518, 319);
    }// </editor-fold>//GEN-END:initComponents

    private void jFileChooser1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFileChooser1ActionPerformed
        try {

            System.out.println(evt.getActionCommand());

            if (JFileChooser.CANCEL_SELECTION.equals(evt.getActionCommand())) {
            // Cancel was clicked

            // Hide dialog
            this.setVisible(false);
        }

            if (evt.getActionCommand().equals("ApproveSelection")) {
                File file = jFileChooser1.getSelectedFile();

                String s = file.getName();
                int i = s.lastIndexOf('.');

                if (i > 0 && i < s.length() - 1) {
                    String extension = s.substring(i + 1).toLowerCase();


                    if ("tiff".equals(extension) || "png".equals(extension) || "gif".equals(extension) || "jpeg".equals(extension) || "jpg".equals(extension)) {

                      file1 = file;                                   
                      addstud.myfile(new ImageIcon(file.getPath()));
                      this.dispose();
                      
                        

                    } else {
                        JOptionPane.showMessageDialog(null, "please select a valid file type");
                    }
                }

            }
 
 
        } catch (Exception e) {

            System.out.println("dffdfd");
        }


}//GEN-LAST:event_jFileChooser1ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        try {
            UIManager.setLookAndFeel(new SyntheticaBlackStarLookAndFeel());
        } catch (Exception e) {
        }
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfilechose().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser jFileChooser1;
    // End of variables declaration//GEN-END:variables

}
