/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * new_group.java
 *
 * Created on May 29, 2010, 1:15:54 PM
 */

package chessimal12;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author PC
 */
public class new_group extends javax.swing.JFrame {
    String ned = "not";

    /** Creates new form new_group */
    public new_group() {
        initComponents();
        t2.setEditable(false);
        b3.setEnabled(false);
        b2.setEnabled(false);

         try {
            Connection con = DB.getMyConnection();
            Statement st = con.createStatement();
             ResultSet rs =  st.executeQuery("select* from groupstr");


                Vector v1 = new Vector();

           while ((rs.next())) {

            v1.add(rs.getString("grName"));
            group.setModel(new DefaultComboBoxModel(v1));

            }
        } catch (Exception e) {
            System.out.println(e);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        group = new javax.swing.JComboBox();
        t1 = new javax.swing.JTextField();
        b1 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        b3 = new javax.swing.JButton();
        t2 = new javax.swing.JTextField();
        b4 = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Add A New Group");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        group.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "group1" }));
        group.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                groupActionPerformed(evt);
            }
        });

        b1.setText("Add");
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });

        b2.setText("Delete this group");
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });

        b3.setText("Update");
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });

        b4.setText("Back to Home");
        b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ActionPerformed(evt);
            }
        });

        jRadioButton1.setText("Update/Delete This Group");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(b4, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(t2)
                            .addComponent(t1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(b3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(b1, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jRadioButton1)
                        .addGap(65, 65, 65)
                        .addComponent(group, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jRadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(group, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b2)
                    .addComponent(b4))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 220));

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-460)/2, (screenSize.height-229)/2, 460, 229);
    }// </editor-fold>//GEN-END:initComponents

    private void groupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_groupActionPerformed
       t1.setText(group.getSelectedItem().toString());
       ned = group.getSelectedItem().toString();
    }//GEN-LAST:event_groupActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
       if(!t1.getText().isEmpty()){
        try {
           Connection con = DB.getMyConnection();
           Statement st = con.createStatement();
           st.executeUpdate("insert into groupstr(grName) values('"+t1.getText()+"')");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"This Group exists");
        }

         try {
            Connection con = DB.getMyConnection();
            Statement st = con.createStatement();
             ResultSet rs =  st.executeQuery("select* from groupstr");


                Vector v1 = new Vector();

           while ((rs.next())) {

            v1.add(rs.getString("grName"));
            group.setModel(new DefaultComboBoxModel(v1));

            }
        } catch (Exception e) {
            System.out.println(e);
        }
       }else{
       JOptionPane.showMessageDialog(null, "Text Field is Empty");
       }
    }//GEN-LAST:event_b1ActionPerformed

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
        if(!t1.getText().equals("")){
        try {
           Connection con = DB.getMyConnection();
           Statement st = con.createStatement();
           st.executeUpdate("update groupstr set grName = '"+t2.getText()+"' where grName = '"+t1.getText()+"'");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"This Group exists");
        }

         try {
            Connection con = DB.getMyConnection();
            Statement st = con.createStatement();
             ResultSet rs =  st.executeQuery("select* from groupstr");


                Vector v1 = new Vector();

           while ((rs.next())) {

            v1.add(rs.getString("grName"));
            group.setModel(new DefaultComboBoxModel(v1));

            }
        } catch (Exception e) {
            System.out.println(e);
        }
        }else{
        JOptionPane.showMessageDialog(null, "The textfield is empty");
        }
    }//GEN-LAST:event_b3ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
  Object[] options = { "Yes", "No" };
int respon = JOptionPane.showOptionDialog(null, "Group date will be lost Are You Sure You want to Proceed", "Warning",JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE,null, options, options[0]);
        
        if(respon==0){
        
        if(!t1.getText().equals("")) {
        try {
           Connection con = DB.getMyConnection();
           Statement st = con.createStatement();
           st.executeUpdate("delete from groupstr where grName = '"+t1.getText()+"'");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"This Group exists");
        }

         try {
            Connection con = DB.getMyConnection();
            Statement st = con.createStatement();
             ResultSet rs =  st.executeQuery("select* from groupstr");


                Vector v1 = new Vector();

           while ((rs.next())) {

            v1.add(rs.getString("grName"));
            group.setModel(new DefaultComboBoxModel(v1));

            }
        } catch (Exception e) {
            System.out.println(e);
        }
        }else{
        JOptionPane.showMessageDialog(null, "The textfield is empty");
        }
        }
    }//GEN-LAST:event_b2ActionPerformed

    private void b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ActionPerformed
     this.dispose();
     new Home1().setVisible(true);
    }//GEN-LAST:event_b4ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        if(jRadioButton1.isSelected()){

        t1.setEditable(false);
        b1.setEnabled(false);
        t2.setEditable(true);
        b3.setEnabled(true);
        b2.setEnabled(true);

        }else{

        t2.setEditable(false);
        b3.setEnabled(false);
        b2.setEnabled(false);
        t1.setEditable(true);
        b1.setEnabled(true);

        }
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new new_group().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JButton b3;
    private javax.swing.JButton b4;
    private javax.swing.JComboBox group;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    // End of variables declaration//GEN-END:variables

}
