/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * profile.java
 *
 * Created on May 19, 2010, 8:16:09 PM
 */

package chessimal12;

import com.mysql.jdbc.Connection;
import de.javasoft.plaf.synthetica.SyntheticaBlackStarLookAndFeel;
import java.sql.Blob;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.ImageIcon;
import javax.swing.UIManager;

import java.sql.DriverManager;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;


/**
 *
 * @author PC
 */
public class profile extends javax.swing.JFrame {
ImageIcon icon;
    /** Creates new form profile */
    public profile() {
        initComponents();
DB.ChangeJframeImage(this);


        DateFormat foramatdate = new SimpleDateFormat("yyyy/MM/dd");
        try {
            Connection con = (Connection) DB.getMyConnection();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("select* from students where stuID ='"+students1.tableSelect+"'");
            while(rs.next()){
               id.setText(rs.getString("stuid"));
               Name.setText(rs.getString("Nameinit"));


               String txt1 = rs.getString("Namefull");
                int l = txt1.length();
                System.out.println(l);
                if(l>43){
                Name1.setText(txt1.substring(0,l/2));
                Name21.setText("- "+txt1.substring(l/2,l));
                }else{
                Name1.setText(txt1);
                 Name21.setText("-");
                }

                Name2.setText(rs.getString("Adress1"));
                 Name3.setText(rs.getString("Adress2"));
                 c.setText(rs.getString("groupStu"));
                 a.setText(rs.getString("Birth"));
                  b.setText(rs.getString("age"));
                  d.setText(rs.getString("joindDate"));
                 e1.setText(rs.getString("rating"));
                 f.setText(rs.getString("fiderating"));
                 g.setText(rs.getString("tel"));
                 Name4.setText(rs.getString("Gender"));
                Blob b1 = (Blob) rs.getBlob("image");
               icon = new ImageIcon(b1.getBytes(1L, (int) b1.length()));
                l1.setIcon(icon);
            }

        } catch (Exception e) {
            System.out.println(e);
        }

        System.out.println(Name1.getText().length());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        l1 = new javax.swing.JLabel();
        Name2 = new javax.swing.JLabel();
        id = new javax.swing.JLabel();
        Name = new javax.swing.JLabel();
        Name1 = new javax.swing.JLabel();
        Name3 = new javax.swing.JLabel();
        g = new javax.swing.JLabel();
        b = new javax.swing.JLabel();
        a = new javax.swing.JLabel();
        c = new javax.swing.JLabel();
        d = new javax.swing.JLabel();
        e1 = new javax.swing.JLabel();
        f = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        Name21 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        Name4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("Age  ");
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 40, -1));

        jLabel8.setText("Group");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, 20));

        jLabel2.setText("Name with Initials ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 67, -1, -1));

        jLabel3.setText("Full Name");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 50, -1));

        jLabel5.setText("Gender");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        jLabel6.setText("Birth Day");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, 20));

        jLabel9.setText("Student ID");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 39, -1, -1));

        jLabel10.setText("Joind Date");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, 20));

        jLabel11.setText("Rating");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, 20));

        jLabel12.setText("Tel");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 70, 20));

        jLabel13.setText("FIDERating");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 66, 20));

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        l1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/no-user.jpg"))); // NOI18N
        l1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        l1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(l1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 160, 160));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 40, 180, 180));

        Name2.setText("qqqqqqqqqqqqqqqqqqq");
        jPanel1.add(Name2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 190, 20));

        id.setText("8");
        jPanel1.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 29, 40, 30));

        Name.setText(":qqqqqqqqqqqqqqqqqqq");
        jPanel1.add(Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 67, 190, 20));

        Name1.setText("qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq");
        jPanel1.add(Name1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 230, 20));

        Name3.setText("qqqqqqqqqqqqqqqqqqq");
        jPanel1.add(Name3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 180, 20));

        g.setText("aaaaaaaaaaaaaaa");
        jPanel1.add(g, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 340, 120, 20));

        b.setText("qqqqqqqqqqqqqqqqqqq");
        jPanel1.add(b, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 180, 20));

        a.setText("qqqqqqqqqqqqqqqqqqq");
        jPanel1.add(a, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 180, 20));

        c.setText("aaaaaaaaaaaaaaa");
        jPanel1.add(c, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, 180, 20));

        d.setText("aaaaaaaaaaaaaaa");
        jPanel1.add(d, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, 140, 20));

        e1.setText("aaaaaaaaaaaaaaa");
        jPanel1.add(e1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, 250, 20));

        f.setText("aaaaaaaaaaaaaaa");
        jPanel1.add(f, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 320, 250, 20));

        jButton2.setText("Print");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 390, 80, -1));

        Name21.setText("qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq");
        jPanel1.add(Name21, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 230, 20));

        jLabel14.setText("Address");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        Name4.setText("qqqqqqqqqqqqqqqqqqq");
        jPanel1.add(Name4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 180, 20));

        jButton1.setText("back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(358, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(133, 133, 133))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 565, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(390, 390, 390)
                .addComponent(jButton1)
                .addContainerGap(28, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-576)/2, (screenSize.height-476)/2, 576, 476);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       this.setVisible(false);
       new students1().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        DateFormat formatdate = new SimpleDateFormat("MMM d, yyyy");
        Date d21 = new Date();


        try {
            String reportSource = "C:Windows/Chess/genaral_details.jrxml";
            Map<String,Object>params = new HashMap<String, Object>();
            params.put("Date1", formatdate.format(d21));
             params.put("id", id.getText());
                 params.put("nameinitials",Name.getText());
                  params.put("fullname",Name1.getText());
                   params.put("fullname1", Name21.getText());
                    params.put("Gender", Name4.getText());
                     params.put("Birthday", a.getText());
                      params.put("Age", b.getText());
                       params.put("Address", Name2.getText());
                        params.put("address1", Name3.getText());
                         params.put("group", c.getText());
                         params.put("rating", e1.getText());


                          params.put("joinddate", d.getText());
                     params.put("fiderating", f.getText());
                      params.put("tel", g.getText());
 params.put("image",icon);



            JasperReport jasperReport = JasperCompileManager.compileReport(reportSource);

            Class.forName("com.mysql.jdbc.Driver").newInstance();
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql:///chessimaldb","root","123");

            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, params,con);
            JasperViewer.viewReport(jasperPrint,false);
            con.close();
        } catch (Exception e) {
           JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {

         try {
            UIManager.setLookAndFeel(new SyntheticaBlackStarLookAndFeel());
        } catch (Exception e) {
        }
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new profile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Name;
    private javax.swing.JLabel Name1;
    private javax.swing.JLabel Name2;
    private javax.swing.JLabel Name21;
    private javax.swing.JLabel Name3;
    private javax.swing.JLabel Name4;
    private javax.swing.JLabel a;
    private javax.swing.JLabel b;
    private javax.swing.JLabel c;
    private javax.swing.JLabel d;
    private javax.swing.JLabel e1;
    private javax.swing.JLabel f;
    private javax.swing.JLabel g;
    private javax.swing.JLabel id;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel l1;
    // End of variables declaration//GEN-END:variables

}
