/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * progress.java
 *
 * Created on May 19, 2010, 8:31:53 PM
 */

package chessimal12;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author PC
 */
public class progress extends javax.swing.JFrame {
    String maxrating;
    static String id11;
  
    public progress() {
        initComponents();
        DB.ChangeJframeImage(this);
        b2.setEnabled(false);



          try {
            Statement st = DB.getMyConnection().createStatement();
            ResultSet rs = st.executeQuery("select max(rating) as maxrate from students");
            while(rs.next()){

          
            maxrating = rs.getString("maxrate");


            }
        } catch (Exception e) {
            System.out.println(e);
        }


        try {
            Statement st = DB.getMyConnection().createStatement();
            ResultSet rs = st.executeQuery("select stuid from students where groupstu = '"+Home1.selectedGroup+"'");
             Vector v1 = new Vector();
             v1.add("select");
            while(rs.next()){
           
            v1.add(rs.getString("stuid"));

            combo.setModel(new DefaultComboBoxModel(v1));


            }
        } catch (Exception e) {
            System.out.println(e);
        }








    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        l5 = new javax.swing.JLabel();
        l1 = new javax.swing.JLabel();
        l6 = new javax.swing.JLabel();
        l7 = new javax.swing.JLabel();
        l3 = new javax.swing.JLabel();
        l4 = new javax.swing.JLabel();
        l8 = new javax.swing.JLabel();
        l9 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        l2 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        b2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        pro3 = new javax.swing.JProgressBar();
        pro1 = new javax.swing.JProgressBar();
        l10 = new javax.swing.JLabel();
        prol = new javax.swing.JLabel();
        prol1 = new javax.swing.JLabel();
        combo = new javax.swing.JComboBox();
        b3 = new javax.swing.JButton();
        rt = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel15.setText("Name ");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 54, 40, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel17.setText("Gender");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 140, 80, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel18.setText("Birth Day");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 79, 80, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel20.setText("Joind Date");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 110, 100, -1));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel21.setText("Rating");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, -1, -1));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel22.setText("Contact");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 60, -1));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel23.setText("FIDE Rating");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, 97, -1));
        jPanel1.add(l5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 260, 14));
        jPanel1.add(l1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, 290, 14));
        jPanel1.add(l6, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 200, 220, 17));
        jPanel1.add(l7, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 205, 20));
        jPanel1.add(l3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 182, 14));
        jPanel1.add(l4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 153, 14));
        jPanel1.add(l8, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, 179, 20));
        jPanel1.add(l9, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 330, 140, 14));

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel24.setText("Address");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 90, -1));
        jPanel1.add(l2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 140, 20));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel12.setText("Rated games played");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, -1, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 38, 450, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Member Progress");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 162, 32));

        jLabel1.setText("ID   :");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, -1, -1));

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 530, 74, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel11.setText("View a general report of the player");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 480, 231, -1));

        b2.setText("Genarate");
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });
        jPanel1.add(b2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 480, 90, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel9.setText("Relative Rating performance");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, 165, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel10.setText("Attendance");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 440, 165, -1));
        jPanel1.add(pro3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 460, 437, 11));
        jPanel1.add(pro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, 437, 11));
        jPanel1.add(l10, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 360, 140, 14));

        prol.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(prol, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 400, 58, 14));

        prol1.setText("ss");
        prol1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        prol1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(prol1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 440, 58, -1));

        combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboActionPerformed(evt);
            }
        });
        jPanel1.add(combo, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, 110, 20));

        b3.setText("More about this player");
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });
        jPanel1.add(b3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 530, -1, -1));

        rt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/aa.png"))); // NOI18N
        jPanel1.add(rt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, -50, 28, 620));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 470, 439, -1));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 510, 439, -1));

        jLabel3.setText(":");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, -1, -1));

        jLabel4.setText(":");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 12, -1));

        jLabel5.setText(":");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 12, -1));

        jLabel6.setText(":");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 138, 10, 20));

        jLabel7.setText(":");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 12, -1));

        jLabel13.setText(":");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, 12, -1));

        jLabel14.setText(":");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 12, -1));

        jLabel16.setText(":");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 330, 10, 10));

        jLabel19.setText(":");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 360, 12, -1));

        jLabel25.setText(":");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, 62, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 513, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-529)/2, (screenSize.height-608)/2, 529, 608);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      this.setVisible(false);
     
    }//GEN-LAST:event_jButton2ActionPerformed

    private void comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboActionPerformed
      b2.setEnabled(true);
      if(!combo.getSelectedItem().toString().equals("select")){
        try {
            Statement st = DB.getMyConnection().createStatement();
            ResultSet rs = st.executeQuery("select Nameinit,Gender,Birth,Adress1,Adress2,tel,rating,fiderating,joindDate,playrated from students where stuid = '"+combo.getSelectedItem().toString()+"'");
            while(rs.next()){
            l1.setText(rs.getString("Nameinit"));
            l2.setText(rs.getString("Gender"));
            l3.setText(rs.getString("Birth"));
            l4.setText(rs.getString("joindDate"));
            l5.setText(rs.getString("Adress1"));
            l6.setText(rs.getString("Adress2"));
            l7.setText(rs.getString("tel"));
            l8.setText(rs.getString("rating"));
            l9.setText(rs.getString("fiderating"));
            l10.setText(rs.getString("playrated"));
                System.out.println(maxrating);

            }

            int pre = (int)((Double.parseDouble(l8.getText())/Double.parseDouble(maxrating))*1000);
            String finala = String.valueOf(((double)pre)/10);

            pro1.setMinimum(0);
            pro1.setMaximum(100);
            pro1.setValue(pre/10);
            prol.setText(finala+"%");

        } catch (Exception e) {
            System.out.println(e);
        }


  try {
            Statement st = DB.getMyConnection().createStatement();
            ResultSet rs = st.executeQuery("select count(id) as count, sum(val) as attende from atten where id = '"+combo.getSelectedItem().toString()+"'");
            while(rs.next()){

                System.out.println(rs.getString("attende"));
                System.out.println(rs.getString("count"));

                int pre1 = (int)((Double.parseDouble(rs.getString("attende"))/Double.parseDouble(rs.getString("count")))*1000);
                String finala = String.valueOf(((double)pre1)/10);
                pro3.setMinimum(0);
                pro3.setMaximum(100);
                pro3.setValue(pre1/10);
                prol1.setText(finala+"%");
            }


        } catch (Exception e) {
            System.out.println(e);
        }
      }
    }//GEN-LAST:event_comboActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
   DateFormat formatdate = new SimpleDateFormat("MMM d, yyyy");
        Date d21 = new Date();


        try {
            String reportSource = "C:Windows/chess/progress_report.jrxml";
            Map<String,Object>params = new HashMap<String, Object>();
                 params.put("Date1", formatdate.format(d21));
                 params.put("id", combo.getSelectedItem().toString());
                 
                 params.put("nameinitials",l1.getText());
                 params.put("Gender", l2.getText());
                 params.put("Birthday", l3.getText());
                 params.put("Address", l5.getText());
                 params.put("address1", l6.getText());
                 params.put("rating", l8.getText());
                 params.put("joinddate", l4.getText());
                 params.put("fiderating", l9.getText());
                 params.put("tel",l7.getText());




            JasperReport jasperReport = JasperCompileManager.compileReport(reportSource);

            Class.forName("com.mysql.jdbc.Driver").newInstance();
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql:///chessimaldb","root","123");

            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, params,con);
            JasperViewer.viewReport(jasperPrint,false);
            con.close();
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_b2ActionPerformed

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
       if(!combo.getSelectedItem().toString().equals("select")){
        id11 = combo.getSelectedItem().toString();
     
        moreplayerdetails g = new moreplayerdetails();
       g.id(id11);
        
        g.gamedetail(id11);
        g.k11();
        

        //g.setVisible(true);
        this.dispose();
       

           
      
       }else{
        JOptionPane.showMessageDialog(null,"please Select a player");
       }
    }//GEN-LAST:event_b3ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new progress().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b2;
    private javax.swing.JButton b3;
    private javax.swing.JComboBox combo;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l10;
    private javax.swing.JLabel l2;
    private javax.swing.JLabel l3;
    private javax.swing.JLabel l4;
    private javax.swing.JLabel l5;
    private javax.swing.JLabel l6;
    private javax.swing.JLabel l7;
    private javax.swing.JLabel l8;
    private javax.swing.JLabel l9;
    private javax.swing.JProgressBar pro1;
    private javax.swing.JProgressBar pro3;
    private javax.swing.JLabel prol;
    private javax.swing.JLabel prol1;
    private javax.swing.JLabel rt;
    // End of variables declaration//GEN-END:variables

}
